### ISSUE TITLE
Add a "parc automobile" module with stock and market penetration rates

### ISSUE THREAD

**Issue by gilgeorges** [observatoire-mobilite/odm-website#46]
### Suggestion
Add a dedicated module, collecting stats about the vehicle fleet.

### Tasks
- [ ] Extract vehicle numbers by propulsion types from `parc_automobile` SNCA data on data.public.lu (formerly #39)
- [ ] Extract new sales per month as `DATCIR==DATCIR_GD`
- [ ] Create bar chart widget
- [ ] Create page module, add widgets and data

**Comment by gilgeorges** [comment]
Donce since #74
